[git]
files = { "git/.gitconfig" = "~/.gitconfig" }

[jj]
files = { "jj/config.toml" = "~/.config/jj/config.toml" }

[micro]
files = { "micro/settings.json" = "~/.config/micro/settings.json", "micro/bindings.json" = "~/.config/micro/bindings.json" }

[cargo]
files = { "cargo/config.toml" = "~/.cargo/config.toml" }

[vscode]
files = { "vscode/settings.json" = "~/.config/Code/User/settings.json", "vscode/keybindings.json" = "~/.config/Code/User/keybindings.json" }

[antigravity]
files = { "antigravity/settings.json" = "~/.config/Antigravity/User/settings.json", "antigravity/keybindings.json" = "~/.config/Antigravity/User/keybindings.json" }

[cursor]
files = { "cursor/settings.json" = "~/.config/Cursor/User/settings.json", "cursor/keybindings.json" = "~/.config/Cursor/User/keybindings.json" }

[bash]
files = { "bash/.bashrc" = "~/.bashrc", "bash/.profile" = "~/.profile", "bash/.bash_logout" = "~/.bash_logout" }
